name: "My site"
language: "en-US"
description: "Description for my site"
navigation:
    - label: "About"
      url: "/about/"
    - label: "Authors"
      url: "/authors/"
    - label: "Tags"
      url: "/tags/"
footer-socials:
  - title: "Instagram"
    url: "https://instagram.com/"
  - title: "Facebook"
    url: "https://facebook.com/"
  - title: "YouTube"
    url: "https://youtube.com/"
  - title: "TikTok"
    url: "https://tiktok.com/"
  - title: "LinkedIn"
    url: "https://linkedin.com/"
  - title: "X"
    url: "https://x.com/"
